name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "31 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ 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 }}
          USERNAME: ${{ github.DevashishPathrabe }}
          MAX_REPOS: 250
      - name: Commit & Push
        run: |
          git config user.name ${{ github.DevashishPathrabe }}
          git config user.email devashishpathrabe@gmail.com
          git add -A .
          git commit -m "GitHub 3D Profile"
          git push
